/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cvut.fel.dbs.lib.gui;

import cvut.fel.dbs.lib.Application;
import cvut.fel.dbs.lib.model.AutoCourse;
import cvut.fel.dbs.lib.model.Instructor;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rufus
 */
public class RelationshipGUI extends javax.swing.JFrame {

    /**
     * Creates new form RelationshipGUI
     */
    public RelationshipGUI() {
        initComponents();
        Application app = new Application();
        app.setup();
        showInstructorsInTable();
        showAutoCourseInTable();
    }
    
    
    Application app2 = new Application();
    
    // Shows instructors from database to tableInstructor
    public void showInstructorsInTable() {
        ArrayList<Instructor> list = app2.getInstructorsList();
        DefaultTableModel model = (DefaultTableModel)tableInstructor.getModel();
        Object[] row = new Object[6];
        for(int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getPersonId();
            row[1] = list.get(i).getName();
            row[2] = list.get(i).getEmployeeNumber();
            row[3] = list.get(i).getWeb();
            row[4] = list.get(i).getPhoneNumber();
            row[5] = list.get(i).getSalary();
            
            model.addRow(row);
        }
    }
    
    // Shows autoCourse from database to tableAutoCourse
    public void showAutoCourseInTable() {
        ArrayList<AutoCourse> list = app2.getAutoCoursesList();
        DefaultTableModel model = (DefaultTableModel)tableAutoCourse.getModel();
        Object[] row = new Object[5];
        for(int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getCode();
            row[2] = list.get(i).getDescription();
            row[3] = list.get(i).getDuration();
            row[4] = list.get(i).getCost();
            
            model.addRow(row);
        }
    }
    
    // Shows courses id from selected instructor 
    public List<AutoCourse> showRelationshipInTable(List<AutoCourse> acList) {
        DefaultTableModel model = (DefaultTableModel)tableRelationship.getModel();
        Object[] row = new Object[1];
        for(int i = 0; i < acList.size(); i++) {
            row[0] = acList.get(i).getId();
            model.addRow(row);
        }  
        return acList;
    }
    
    //Check if integer
    public static boolean isInteger(String s) {
        boolean isValidInteger = false;
        try
        {
            Integer.parseInt(s);
 
            isValidInteger = true;
        }
        catch (NumberFormatException ex)
        {
            return isValidInteger;
        }
 
        return isValidInteger;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bttnChangeFrameToInstructor = new javax.swing.JButton();
        labelRelationshipPage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRelationship = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableInstructor = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableAutoCourse = new javax.swing.JTable();
        labelInstructorId = new javax.swing.JLabel();
        labelAutoCourseId = new javax.swing.JLabel();
        tfInstructorId = new javax.swing.JTextField();
        tfAutoCourseId = new javax.swing.JTextField();
        bttnCreate = new javax.swing.JButton();
        bttnDelete = new javax.swing.JButton();
        labelError = new javax.swing.JLabel();
        bttnRead = new javax.swing.JButton();
        labelInstructorRead = new javax.swing.JLabel();
        tfInstructorIdRead = new javax.swing.JTextField();
        errorLabelRead = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bttnChangeFrameToInstructor.setText("Instructor page");
        bttnChangeFrameToInstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnChangeFrameToInstructorActionPerformed(evt);
            }
        });

        labelRelationshipPage.setText("Relationship page");

        tableRelationship.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AutoCourseId"
            }
        ));
        jScrollPane1.setViewportView(tableRelationship);

        tableInstructor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Employee№", "Web", "Phone№", "Salary"
            }
        ));
        jScrollPane2.setViewportView(tableInstructor);

        tableAutoCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Code", "Description", "Duration", "Cost"
            }
        ));
        jScrollPane3.setViewportView(tableAutoCourse);

        labelInstructorId.setText("Instructor Id:");

        labelAutoCourseId.setText("AutoCourse Id:");

        tfAutoCourseId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAutoCourseIdActionPerformed(evt);
            }
        });

        bttnCreate.setText("Create");
        bttnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCreateActionPerformed(evt);
            }
        });

        bttnDelete.setText("Delete");
        bttnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnDeleteActionPerformed(evt);
            }
        });

        bttnRead.setText("Read");
        bttnRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnReadActionPerformed(evt);
            }
        });

        labelInstructorRead.setText("Instructor Id:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(bttnChangeFrameToInstructor)
                        .addGap(80, 80, 80)
                        .addComponent(labelRelationshipPage))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelInstructorId)
                                        .addComponent(labelAutoCourseId))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfAutoCourseId, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                        .addComponent(tfInstructorId)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(bttnCreate)
                                    .addGap(12, 12, 12)
                                    .addComponent(bttnDelete))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelInstructorRead)
                                    .addGap(10, 10, 10)
                                    .addComponent(tfInstructorIdRead))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelError)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(bttnRead)
                                    .addGap(18, 18, 18)
                                    .addComponent(errorLabelRead)))
                            .addComponent(errorLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnChangeFrameToInstructor)
                    .addComponent(labelRelationshipPage))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelInstructorId)
                            .addComponent(tfInstructorId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelAutoCourseId)
                            .addComponent(tfAutoCourseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bttnCreate)
                            .addComponent(bttnDelete))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelError)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(errorLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelInstructorRead)
                                    .addComponent(tfInstructorIdRead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bttnRead)
                                    .addComponent(errorLabelRead)))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Change Frame Relationship to GUI frame
    private void bttnChangeFrameToInstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnChangeFrameToInstructorActionPerformed
        new GUI().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bttnChangeFrameToInstructorActionPerformed

    private void tfAutoCourseIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAutoCourseIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAutoCourseIdActionPerformed
    
    // Button read shows all courses from selected instructor
    private void bttnReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnReadActionPerformed
        app2.setup();
        if(tfInstructorIdRead.getText().trim().isEmpty() || !isInteger(String.valueOf(tfInstructorIdRead.getText()))) {
            errorLabelRead.setText("Instructor id isn't correct.");
            errorLabelRead.setVisible(true);
        } else {
            try{
                errorLabelRead.setVisible(false);
                Long personId = Long.valueOf(tfInstructorIdRead.getText());
            
                Instructor ins = app2.findIns(personId);
            
                if(ins.getPersonId() == null){
                    errorLabelRead.setText("Didn't find instructor.");
                    errorLabelRead.setVisible(true);
                    DefaultTableModel model = (DefaultTableModel)tableRelationship.getModel();
                    model.setRowCount(0);
                } else {
                
                    app2.getTransactionBegin();
                    List<AutoCourse> acList = ins.getInstructoredAutoCourses();
                    app2.getTransactionCommit();
                
                    DefaultTableModel model = (DefaultTableModel)tableRelationship.getModel();
                    model.setRowCount(0);
                    showRelationshipInTable(acList);
                }
            } catch (Exception ex) {
                System.out.print(ex);
            } finally {
                app2.close();
            }
        }
    }//GEN-LAST:event_bttnReadActionPerformed

    // Button Create - create relatiionship (instructor, autocourse)
    private void bttnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCreateActionPerformed
        app2.setup();
        if(tfInstructorId.getText().trim().isEmpty() || !isInteger(String.valueOf(tfInstructorId.getText()))) {
            errorLabel.setText("Instructor id isn't correct.");
            errorLabel.setVisible(true);
        } else if (tfAutoCourseId.getText().trim().isEmpty() || !isInteger(String.valueOf(tfAutoCourseId.getText()))){
            errorLabel.setText("AutoCourse id isn't correct.");
            errorLabel.setVisible(true);
        } else {
            try{
                errorLabel.setVisible(false);
                errorLabelRead.setVisible(false);
                Long personId = Long.valueOf(tfInstructorId.getText());
                Long acId = Long.valueOf(tfAutoCourseId.getText());
                Instructor ins = app2.findIns(personId);
                AutoCourse ac = app2.findAutoCourse(acId);
                if(ins.getPersonId() == null || ac.getId() == null){
                    errorLabel.setText("Didn't find instructor or course.");
                    errorLabel.setVisible(true);
                } else {
                    errorLabel.setVisible(false);
                    Boolean b = app2.addAutoCourseToInstructor(ins, ac);
                    if (b == false) {
                        errorLabel.setText("Already exists.");
                        errorLabel.setVisible(true);
                    } else {
                        errorLabel.setVisible(false);
                    }
                }
            }catch (Exception ex) {
                System.out.print(ex);
            } finally {
                app2.close();
            }
        }
        
    }//GEN-LAST:event_bttnCreateActionPerformed
    
    // Button Delete - delete relatiionship (instructor, autocourse)
    private void bttnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnDeleteActionPerformed
        app2.setup();
        if(tfInstructorId.getText().trim().isEmpty()|| !isInteger(String.valueOf(tfInstructorId.getText()))) {
            errorLabel.setText("Instructor id isn't correct.");
            errorLabel.setVisible(true);
        } else if (tfAutoCourseId.getText().trim().isEmpty() || !isInteger(String.valueOf(tfAutoCourseId.getText()))){
            errorLabel.setText("AutoCourse id isn't correct.");
            errorLabel.setVisible(true);
        } else {
            try{
                errorLabel.setVisible(false);
                errorLabelRead.setVisible(false);
                Long personId = Long.valueOf(tfInstructorId.getText());
                Long acId = Long.valueOf(tfAutoCourseId.getText());
                Instructor ins = app2.findIns(personId);
                AutoCourse ac = app2.findAutoCourse(acId);
                if(ins.getPersonId() == null || ac.getId() == null){
                    errorLabel.setText("Didn't find instructor or course.");
                    errorLabel.setVisible(true);
                } else {
                    errorLabel.setVisible(false);
                    Boolean b = app2.deleteAutoCourseFromInstructor(ins, ac);
                    if (b == false) {
                        errorLabel.setText("Doesn't exist.");
                        errorLabel.setVisible(true);
                    } else {
                        errorLabel.setVisible(false);
                    }
                }
            }catch (Exception ex) {
                System.out.print(ex);
            } finally {
                app2.close();
            }
        }
    }//GEN-LAST:event_bttnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelationshipGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelationshipGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelationshipGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelationshipGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelationshipGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnChangeFrameToInstructor;
    private javax.swing.JButton bttnCreate;
    private javax.swing.JButton bttnDelete;
    private javax.swing.JButton bttnRead;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel errorLabelRead;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelAutoCourseId;
    private javax.swing.JLabel labelError;
    private javax.swing.JLabel labelInstructorId;
    private javax.swing.JLabel labelInstructorRead;
    private javax.swing.JLabel labelRelationshipPage;
    private javax.swing.JTable tableAutoCourse;
    private javax.swing.JTable tableInstructor;
    private javax.swing.JTable tableRelationship;
    private javax.swing.JTextField tfAutoCourseId;
    private javax.swing.JTextField tfInstructorId;
    private javax.swing.JTextField tfInstructorIdRead;
    // End of variables declaration//GEN-END:variables
}
